# Generated by Django 4.0 on 2021-12-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biblioteca',
            new_name='Bibliotecas',
        ),
    ]
